# Copyright (c) 2022 STMicroelectronics
# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: openamp
      url-base: https://github.com/OpenAMP
    - name: zephyr
      url-base: https://github.com/zyphyrproject-rtos
  defaults:
    remote: openamp

  self:
    path: openamp-system-reference

  projects:
    - name: zephyr
      remote: zephyr
      revision: 356c8cbe63ae01b3ab438382639d25bb418a0213
      import: true
